name: ml-deploy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - fastapi
  - flaml
  - jupyterlab
  - uvicorn
  - boto3
  - joblib
  - pandas
  - pytest
  - pyyaml
  - requests
  - scikit-learn
  - dvc
  - pre-commit
  - black
  - pip:
    - gunicorn
